update regex

diff --git a/.github/workflows/linear_pr_title.yaml b/.github/workflows/linear_pr_title.yaml
--- a/.github/workflows/linear_pr_title.yaml
+++ b/.github/workflows/linear_pr_title.yaml
@@ -9,11 +9,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check PR title
-      run: |
-        title="${{ github.event.pull_request.title }}"
-        pattern="^LF-[0-9]+:.*"
-        if [[ ! ${title} =~ ${pattern} ]]; then
-          echo "Error: The PR title does not link a linear issue like: LF-123: My PR title"
-          exit 1
-        fi
+      - name: Check PR title
+        run: |
+          title="${{ github.event.pull_request.title }}"
+          pattern="^\[?LF-[\d]+\]?[: ].*"
+          if [[ ! ${title} =~ ${pattern} ]]; then
+            echo "Error: The PR title does not link a linear issue like: LF-123: My PR title"
+            exit 1
+          fi
